title: SDBudget
# http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
baseurl: '/sd-budget'
exclude: ['README.md']
show_downloads: false
github:
        is_project_page: false
        is_user_page: true
sass:
        sass_dir: _sass

primary_navigation:
        - title: SDBudget
          url: /index.html#about
        - title: Download
          url: /index.html#download
        - title: FAQ
          url: /index.html#faq

secondary_navigation:
        - title: Documentation
          url: /documentation.html
        - title: Changelog
          url: /changelog.html

download:
        filepath: /assets/download/sdbudget-0.3.0.zip
        version: 0.3.0